name: cibuildwheel

on: [workflow_dispatch]

# env:
#   global:
#     - CIBW_SKIP="cp36-* cp37-* cp38-* cp39-* cp310-*"

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        os: [ubuntu-latest]
        build: [cp310-*, cp311-*, cp312-*, cp313-*]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir=wheelhouse

      - uses: actions/upload-artifact@v
        with:
          name: cibw-wheel-${{matrix.os}}-${{strategy.job-index}}
          path: wheelhouse/*whl
